script_path: scripts/run_ner.py
dataset_name: eduagarcia/cnj_benchmarks
do_train: true
do_eval: true
do_predict: true
per_device_train_batch_size: 16
learning_rate: 1e-5
warmup_steps: 100
num_train_epochs: 15
#max_steps: 10000
evaluation_strategy: steps
save_strategy: steps
eval_steps: 500
save_steps: 500
save_total_limit: 1
metric_for_best_model: "f1"
greater_is_better: "True"
load_best_model_at_end: True
weight_decay: 0.01
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1e-6
early_stopping_patience: 3
early_stopping_threshold: 0.001
max_seq_length: 256
break_docs_to_max_length: True
#no_label_all_tokens: True
#use_crf: True
#convert_to_iobes: True
#learning_rate_ner: 1e-3
